source 'https://rubygems.org'
ruby '~> 2.7'

gem 'builder', '~> 3.1.4'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-sqs', '~> 1'
gem 'dentaku', '~> 3.4.1'
gem 'json', '~> 2.3'
gem 'mime-types', '~> 3.1'
gem 'multipart-post', '~> 2.1.1'
gem 'require_all', '~> 1.4.0'
gem 'bigdecimal', '1.4.4'
