AllCops:
  NewCops: enable

Layout/IndentationStyle:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/MethodLength:
  Max: 100

Layout/LineLength:
  Max: 80

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 500

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 500

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# don't allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# it's okay that Rakefile is capitalized
Naming/FileName:
  Exclude:
    - 'Rakefile.rb'
