version: '2'
services:
  rspec:
    image: moviemasher/moviemasher.rb.rspec:4.0.26
    container_name: moviemasher_rspec
    build:
      context: ../../../
      dockerfile: ./config/docker/rspec/Dockerfile-rspec
    volumes:
      - ../../../lib:/mnt/moviemasher.rb/lib
      - ../../../.rspec:/mnt/moviemasher.rb/.rspec
      - ../../../service:/mnt/moviemasher.rb/service
      - ../../../spec:/mnt/moviemasher.rb/spec
      - ../../../tmp:/mnt/moviemasher.rb/tmp
      - ../../../config:/mnt/moviemasher.rb/config
      - ../../../../angular-moviemasher:/mnt/angular-moviemasher
      - ../../../../moviemasher.js:/mnt/angular-moviemasher/node_modules/@moviemasher/moviemasher.js
    links:
      - localstack
      - http
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: '...'
      AWS_SECRET_ACCESS_KEY: '...'
  http:
    image: php:apache
    container_name: moviemasher_http
    volumes:
      - ./http/:/var/www/html
    ports:
      - "8888:80"
  localstack:
    image: localstack/localstack
    container_name: moviemasher_localstack
    environment:
      SERVICES: s3,sqs
      HOSTNAME_EXTERNAL: localstack
      DEFAULT_REGION: us-east-1
